language: node_js
cache: yarn
node_js:
  - "10"
  - "8"
  - "6"
env:
  - ESLINT_VERSION=current
  - ESLINT_VERSION=^5
  - ESLINT_VERSION=^4
  - ESLINT_VERSION=^3
install:
  - if [[ $ESLINT_VERSION != "current" ]]; then
    yarn upgrade "eslint@$ESLINT_VERSION";
    fi
  - yarn install
  - yarn run --silent eslint --version
